# Logistic Regression Model

### Step 1: Import Dependences and Read in the TX_population_price_income.csv dataset

In [1]:
# Import the modules and/or dependencies for the model
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn import utils

In [2]:
# Import and read the CSV file from the Resources Folder into a Pandas DataFrame
#import boto3

# AWS S3 Keys and bucket
#aws_access_key_id = "AKIA5NM2LZY7AKLH3DEV"
#aws_secret_access_key = "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"
#bucket_name = "txsqlbucket"
#file_key = "TX_population_price_income.csv"

# Initialize S3 client
#s3 = boto3.client('s3', aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key)

# Transfer CSV from S3 to a local file
#local_file_path = 'local_file.csv'
#s3.download_file(bucket_name, file_key, local_file_path)

#Read CSV File from S3 and convert into a DataFrame
#df = pd.read_csv(local_file_path)

#df.head()

In [3]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
df = pd.read_csv(
    Path(r"C:\Users\gurpa\Documents\GitHub\project-4-group-3\Resources\Datasets\TX_population_price_income.csv")   
)

# Review the DataFrame
df.head()

zipcode  latitude  longitude        city state  population  density  \
0    75001  32.96015  -96.83808     Addison    TX     16287.0   1675.8   
1    75002  33.08946  -96.60639       Allen    TX     71102.0    730.5   
2    75006  32.96165  -96.89717  Carrollton    TX     48104.0   1087.9   
3    75007  33.00498  -96.89590  Carrollton    TX     54448.0   1765.6   
4    75009  33.33840  -96.75185      Celina    TX     24737.0     96.8   

  state_x        City         P_2015         P_2016         P_2017  \
0      TX     Addison  273859.578248  295281.261346  319308.556028   
1      TX       Allen  239753.959055  264265.549908  284191.718651   
2      TX  Carrollton  166228.034235  190571.631296  211957.412770   
3      TX  Carrollton  202984.628681  229672.379983  252570.849051   
4      TX      Celina  280691.570208  310914.564739  336086.422557   

          P_2018         P_2019         P_2020         P_2021         P_2022  \
0  332937.394421  333861.351907  339818.071981  378728.238689  440760.626322   
1  296218.093998  296925.018846  305948.221490  360917.024084  456706.808768   
2  230517.640102  237664.547886  247785.264211  278907.454892  332128.562201   
3  270069.177898  275111.240888  285478.082796  325031.654801  389614.500264   
4  346691.188607  347364.967716  354443.470226  428784.450364  567323.669790   

          P_2023  Net_Income  
0  454387.585703     31081.0  
1  464720.114745     97936.0  
2  341701.767495    115491.0  
3  400732.127660    100570.0  
4  557517.038561     16893.0

#### Minor fixtures to dataset

In [4]:
# Drop any null or empty values
df=df.dropna(how='any')

In [5]:
# Convert datatype of y data from float to int
df = df.astype({"P_2023":int},errors="raise")

### Step 2: Split the data into X and y variables, and then into training and testing sets

In [6]:
# Separate the data into labels and features

# Create a y variable and use the P_2023 column as the label
y = df['P_2023'].values.reshape(-1,1)

# Create an X variable and use all other columns as features
X = df.drop(['P_2023', 'city', 'City', 'state', 'state_x'], axis = 1)

In [7]:
# Review the y variable series
y[:]

array([[454387],
       [464720],
       [341701],
       ...,
       [217041],
       [199986],
       [238718]])

In [8]:
# Review the X variable DataFrame
X.head()

zipcode  latitude  longitude  population  density         P_2015  \
0    75001  32.96015  -96.83808     16287.0   1675.8  273859.578248   
1    75002  33.08946  -96.60639     71102.0    730.5  239753.959055   
2    75006  32.96165  -96.89717     48104.0   1087.9  166228.034235   
3    75007  33.00498  -96.89590     54448.0   1765.6  202984.628681   
4    75009  33.33840  -96.75185     24737.0     96.8  280691.570208   

          P_2016         P_2017         P_2018         P_2019         P_2020  \
0  295281.261346  319308.556028  332937.394421  333861.351907  339818.071981   
1  264265.549908  284191.718651  296218.093998  296925.018846  305948.221490   
2  190571.631296  211957.412770  230517.640102  237664.547886  247785.264211   
3  229672.379983  252570.849051  270069.177898  275111.240888  285478.082796   
4  310914.564739  336086.422557  346691.188607  347364.967716  354443.470226   

          P_2021         P_2022  Net_Income  
0  378728.238689  440760.626322     31081.0  
1  360917.024084  456706.808768     97936.0  
2  278907.454892  332128.562201    115491.0  
3  325031.654801  389614.500264    100570.0  
4  428784.450364  567323.669790     16893.0

In [9]:
# Split into testing and training sets using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

### Step 3: Fit a Logistic Regression Classifier

In [10]:
lab = preprocessing.LabelEncoder()
y_transformed_train = lab.fit_transform(y_train)

C:\Users\gurpa\anaconda3\envs\dev\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
# Declare a logistic regression model.
# Apply a random_state of 9 to the model
logistic_regression_model = LogisticRegression(random_state=42)

# Fit and save the logistic regression model using the training data
lr_model = logistic_regression_model.fit(X_train, y_transformed_train)

C:\Users\gurpa\anaconda3\envs\dev\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Step 4: Create predicted values for training and testing data

In [12]:
#Generate training predictions
training_predictions = lr_model.predict(X_train)

#Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)

### Step 5: Print confusion matric for the training data.

In [13]:
# Create and save the confusion matrix for the training data
training_matrix = confusion_matrix(y_transformed_train, training_predictions)

# Print the confusion matrix for the training data
print(training_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


### Step 6: Print confusion matric for the testing data.

In [14]:
# Create and save the confusion matrix for the testing data
test_matrix = confusion_matrix(y_test, testing_predictions)

# Print the confusion matrix for the testing data
print(test_matrix)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Step 7: Print the training classification report.

In [15]:
# Create and save the training classification report
training_report = classification_report(y_transformed_train, training_predictions)

# Print the training classification report
print(training_report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1
           3       1.00      1.00      1.00         1
           4       0.00      0.00      0.00         1
           5       0.33      1.00      0.50         1
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          10       0.25      1.00      0.40         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          14       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         1
          17       0.00    

C:\Users\gurpa\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gurpa\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gurpa\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Step 8: Print the testing classification report.

In [16]:
# Create and save the testing classification report
testing_report = classification_report(y_test, testing_predictions)

# Print the testing classification report
print(testing_report)

              precision    recall  f1-score   support

           3       0.00      0.00      0.00       0.0
           5       0.00      0.00      0.00       0.0
          10       0.00      0.00      0.00       0.0
          25       0.00      0.00      0.00       0.0
          27       0.00      0.00      0.00       0.0
          29       0.00      0.00      0.00       0.0
          30       0.00      0.00      0.00       0.0
          36       0.00      0.00      0.00       0.0
          39       0.00      0.00      0.00       0.0
          43       0.00      0.00      0.00       0.0
          44       0.00      0.00      0.00       0.0
          45       0.00      0.00      0.00       0.0
          46       0.00      0.00      0.00       0.0
          53       0.00      0.00      0.00       0.0
          54       0.00      0.00      0.00       0.0
          57       0.00      0.00      0.00       0.0
          66       0.00      0.00      0.00       0.0
          72       0.00    

C:\Users\gurpa\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gurpa\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gurpa\anaconda3\envs\dev\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\gurpa\anaconda3\envs\dev\li